CREATE TABLE book (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      isbn VARCHAR(13) NOT NULL UNIQUE,
      title VARCHAR(255) NOT NULL,
      author VARCHAR(255) NOT NULL,
      price DOUBLE NOT NULL CHECK (price > 0),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      last_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
      version INT NOT NULL,
      CONSTRAINT chk_isbn_format CHECK (LENGTH(isbn) = 10 OR LENGTH(isbn) = 13)
);