server:
  port: 8081

spring:
  application:
    name: springboot-basic-board-2
  datasource:
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mappers/*.xml