apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
        - name: edge-service
          image: edge-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9000
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:80
            - name: WEB_FRONT_SERVICE_URL
              value: http://web-front-service:80
            - name: CATALOG_SERVICE_URL
              value: http://catalog-service:80
            - name: ORDER_SERVICE_URL
              value: http://order-service:80
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888
            - name: SPRING_REDIS_HOST
              value: polar-redis